apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-az-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-az-python 
  name: test-az-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-az-python 
